### PR TITLE
Feature: Use PadDataExtractor with other extractors (Selective, Random, ...)

### PR DESCRIPTION
**Pull request by soomy**
Just in case you want to use Padding of Selective / Random data.

Made some changes to the PadPatchDataExtractor:
- Works with SliceIndexing
- Renamed to PadDataExtractor
- PadDataExtractor no longer reads data on his own; Use the extractor parameter to load data with other miapy extractors (e. g. SelectiveData- or RandomDataExtractor, ...)

### CODE REVIEW

**Comment by fabianbalsiger** [comment]
Thank you Yannick for your pull request. I like the idea and see the benefit. However, we might need to introduce a base class `DataExtractor` that inherits from `Extractor`. 
Also, what do you think of https://github.com/rundherum/pymia/pull/2/commits/babc33c8f7404829441f6c90a859c531b6feb3f4 @alainjungo, wasn't there something? Please comment

**Comment by fabianbalsiger** [comment]
Ok, for now we will merge it and then rethink the data extraction. Decorating it might just be the right and cleanest thing.
Let's wait for the response of Yannick regarding https://github.com/rundherum/pymia/pull/2/commits/babc33c8f7404829441f6c90a859c531b6feb3f4

**Comment by soomy** [comment]
Yes, thats a valid point. Consequently, it should be added to the parameter definition of the function - forgot about that.

**Comment by fabianbalsiger** [comment]
Just found something we could improve. Suppose to instantiate a `PadDataExtractor` like this:

`PadDataExtractor(padding=(0, 0, 0), categories=('mask_fg', 'mask_t1h2o'),
                               extractor=pymia_extr.DataExtractor(categories=('mask_fg', 'mask_t1h2o')))`

We need to pass the `categories` to both the `PadDataExtractor` and its `extractor` argument. Maybe only pass the class type (i.e., `extractor=pymia_extr.DataExtractor`) and instantiate the extractor in the constructor of the `PadDataExtractor`.

**Comment by fabianbalsiger** [comment]
> Just found something we could improve. Suppose to instantiate a `PadDataExtractor` like this:
> 
> `PadDataExtractor(padding=(0, 0, 0), categories=('mask_fg', 'mask_t1h2o'), extractor=pymia_extr.DataExtractor(categories=('mask_fg', 'mask_t1h2o')))`
> 
> We need to pass the `categories` to both the `PadDataExtractor` and its `extractor` argument. Maybe only pass the class type (i.e., `extractor=pymia_extr.DataExtractor`) and instantiate the extractor in the constructor of the `PadDataExtractor`.

I got it wrong, thanks to @alainjungo . The `PadDataExtractor` should not have a `categories` argument. It can use `self.extractor.categories`.

**Pull request merged**
